module.exports={
    Login:"login",
    Logout:'logout',
    GatewayLogin:"gatewayLogin",
    Data:"data",
    ExecActionComplete:"execActionComplete",
    ExecCommandComplete:"execCommadComplete",
    Drain:"drain",
    CommandIdle:'commandIdle',
    TaskComplete:"taskComplete",
    Error:"error"
};